# Generated by Django 5.2.1 on 2025-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraudio_user_predictionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraudio',
            name='converted_wav',
        ),
        migrations.RemoveField(
            model_name='useraudio',
            name='original_file',
        ),
        migrations.AddField(
            model_name='useraudio',
            name='original_filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
