# Generated by Django 5.2.1 on 2025-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraudio_converted_wav_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='audio',
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='original_filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='UserAudio',
        ),
    ]
