version: '3.9'

services:
  web:
    build: .
    container_name: django_tensorflow_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn music_backend.wsgi:application --bind 0.0.0.0:8000
