version: '3.9'

services:
  web:
    build: .
    container_name: django_tensorflow_app
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MODELS_DIR=/app/models
      - PYTHONPATH=/app/backend
    command: gunicorn music_backend.wsgi:application --bind 0.0.0.0:8000
